apiVersion: apps/v1
kind: Deployment
metadata:
  name: todolistmongodb
  labels:
    app: todolistmongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todolistmongodb
  template:
    metadata:
      labels:
        app: todolistmongodb
    spec:
      containers:
      - name: todolistmongodb
        image: tevolvers/todolist:1.7
        env:
          - name: DB_CONNECT
            value: mongodb://mongodb:27017
        ports:
        - containerPort: 3000
      