apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: todolist-replicaset
  labels:
    app: todolist
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todolist
  template:
    metadata:
      labels:
        app: todolist
    spec:
      containers:
      - name: todolist
        image: ranga/todolist
        ports:
          - containerPort: 80